# Generated by Django 3.2.16 on 2022-10-25 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_country_flag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coun_name',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Country',
        ),
    ]
