# Generated by Django 3.2.16 on 2022-10-26 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20221025_2323'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Coun_name',
        ),
    ]
