# Generated by Django 3.2.16 on 2022-10-27 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_country_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
